### ISSUE TITLE
(2) Fix Map of connected players

### ISSUE THREAD

**Issue by rulojuka** [rulojuka/sbking#65]
There was a `connections.get(validUUID)` returned `null`on a `KryonetSBKingServer`. Check this and convince yourself it is correct.

```
Exception in thread "Server" java.lang.IllegalArgumentException: connectionWithIdentifier should not be null
	at br.com.sbk.sbking.networking.kryonet.KryonetSBKingServer.sendOneTo(KryonetSBKingServer.java:92)
	at br.com.sbk.sbking.networking.kryonet.KryonetSBKingServer.sendOneTo(KryonetSBKingServer.java:85)
	at br.com.sbk.sbking.networking.kryonet.KryonetSBKingServer.sendIsSpectatorTo(KryonetSBKingServer.java:115)
	at br.com.sbk.sbking.networking.server.SBKingServer.sendIsSpectatorTo(SBKingServer.java:112)
	at br.com.sbk.sbking.networking.server.Table.unsit(Table.java:68)
	at br.com.sbk.sbking.networking.server.Table.moveToSeat(Table.java:47)
	at br.com.sbk.sbking.networking.server.Table.moveToSeat(Table.java:38)
	at br.com.sbk.sbking.networking.server.SBKingServer.moveToSeat(SBKingServer.java:63)
	at br.com.sbk.sbking.networking.kryonet.KryonetSBKingServer.onMessage(KryonetSBKingServer.java:71)
	at br.com.sbk.sbking.networking.kryonet.KryonetServerListenerFactory$1.received(KryonetServerListenerFactory.java:88)
	at com.esotericsoftware.kryonet.Server$1.received(Server.java:61)
	at com.esotericsoftware.kryonet.Connection.notifyReceived(Connection.java:246)
	at com.esotericsoftware.kryonet.Server.update(Server.java:208)
	at com.esotericsoftware.kryonet.Server.run(Server.java:356)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by rulojuka** [comment]
There is a NULL checking both on [Table](https://github.com/rulojuka/sbking/blob/c905dad0d09622d4869626516014bc1f9243ecde/src/main/java/br/com/sbk/sbking/networking/server/Table.java#L34) and [SBKingServer](https://github.com/rulojuka/sbking/blob/c905dad0d09622d4869626516014bc1f9243ecde/src/main/java/br/com/sbk/sbking/networking/server/SBKingServer.java#L64). Also, the `.put()` of the HashMap removes previous element if you add a key that is already inside, so in this case, it is also impossible to have a player seated in two seats.

In resume, this is already fixed.
